In [7]:
import numpy as np
# Each row is a training example , each column is a feature [X1 , X2 , X3]
X=np.array (([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y=np.array (([0],[1],[1],[0]), dtype=float)


# Define useful functions
# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))
# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

class NeuralNetwork:
    def __init__(self , x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np.zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input , self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y-self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    def train(self , X, y):
        self.output = self.feedforward ()
        self.backprop ()
        
NN = NeuralNetwork(X,y)
for i in range(1500): # trains the NN 1,000 times
    if i % 50 ==0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward ()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward ())))) #mean sum squared loss
        print ("\n")
NN.train(X, y)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.79460132]
 [0.84045415]
 [0.83030651]
 [0.86190036]]
Loss: 
0.3571285618667454


for iteration # 50

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.79460132]
 [0.84045415]
 [0.83030651]
 [0.86190036]]
Loss: 
0.3571285618667454


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.79460132]
 [0.84045415]
 [0.83030651]
 [0.86190036]]
Loss: 
0.3571285618667454


for iteration # 150

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.79460132]
 [0.84045415]
 [0.83030651]
 [0.86190036]]
Loss: 
0.3571285618667454


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
